"""current stats added

Revision ID: 165832e28d4a
Revises: a05c5916d1c7
Create Date: 2026-02-21 19:17:26.812680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '165832e28d4a'
down_revision: Union[str, None] = 'a05c5916d1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('game_units', sa.Column('current_stats', sa.JSON(), nullable=True))
    # Update existing rows with empty dict as default
    op.execute("UPDATE game_units SET current_stats = '{}' WHERE current_stats IS NULL")
    # Now make it NOT NULL
    op.alter_column('game_units', 'current_stats', existing_type=sa.JSON(), nullable=False)
    op.alter_column('game_units', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_units', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('game_units', 'current_stats')
    # ### end Alembic commands ###
