"""

Revision ID: 227ccd292cc0
Revises: 917e0d071b57
Create Date: 2025-09-10 15:00:38.074401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227ccd292cc0'
down_revision: Union[str, None] = '917e0d071b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_status', sa.Column('turn_deadline', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_status', 'turn_deadline')
    # ### end Alembic commands ###
