"""added crit boost field to game unit model

Revision ID: 377e4929c54f
Revises: 5ea62654b91e
Create Date: 2026-03-27 14:32:20.710650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377e4929c54f'
down_revision: Union[str, None] = '5ea62654b91e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
