"""

Revision ID: 48d14f9d7b04
Revises: 983ea2cfa5ad
Create Date: 2025-09-07 18:35:00.050107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d14f9d7b04'
down_revision: Union[str, None] = '983ea2cfa5ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('portrait_credits', sa.JSON(), nullable=False))
    op.add_column('units', sa.Column('sprite_credits', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'sprite_credits')
    op.drop_column('units', 'portrait_credits')
    # ### end Alembic commands ###
