"""added gamemapstate

Revision ID: 5ea62654b91e
Revises: da9c69976cb4
Create Date: 2026-03-26 00:58:44.119058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea62654b91e'
down_revision: Union[str, None] = 'da9c69976cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_map_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('weather_tiles', sa.JSON(), nullable=False),
    sa.Column('hazard_tiles', sa.JSON(), nullable=False),
    sa.Column('room_effect_tiles', sa.JSON(), nullable=False),
    sa.Column('terrain_effect_tiles', sa.JSON(), nullable=False),
    sa.Column('field_effect_tiles', sa.JSON(), nullable=False),
    sa.Column('item_id_tiles', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_map_states')
    # ### end Alembic commands ###
