"""add move_pp

Revision ID: 63a566ec3ab0
Revises: 48576b620698
Create Date: 2026-02-26 23:54:28.807393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a566ec3ab0'
down_revision: Union[str, None] = '48576b620698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_units', sa.Column('move_pp', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_units', 'move_pp')
    # ### end Alembic commands ###
