"""Add sound_based to Move model

Revision ID: 708321581b71
Revises: c2b6b6f8a1d7
Create Date: 2026-02-26 18:56:51.980646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708321581b71'
down_revision: Union[str, None] = 'c2b6b6f8a1d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moves', sa.Column('sound_based', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moves', 'sound_based')
    # ### end Alembic commands ###
