"""

Revision ID: 917e0d071b57
Revises: 48d14f9d7b04
Create Date: 2025-09-10 14:17:42.780884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917e0d071b57'
down_revision: Union[str, None] = '48d14f9d7b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('turn_seconds', sa.Integer(), nullable=True))
    op.execute("UPDATE games SET turn_seconds = 300 WHERE turn_seconds IS NULL")
    op.alter_column('games', 'turn_seconds', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'turn_seconds')
    # ### end Alembic commands ###
