"""add level to GameUnit

Revision ID: a05c5916d1c7
Revises: 227ccd292cc0
Create Date: 2026-02-21 18:28:26.602283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05c5916d1c7'
down_revision: Union[str, None] = '227ccd292cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_units', sa.Column('level', sa.Integer(), nullable=True))
    # Set default level to 50 for all existing rows
    op.execute("UPDATE game_units SET level = 50 WHERE level IS NULL")
    # Make the column non-nullable
    op.alter_column('game_units', 'level', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_units', 'level')
    # ### end Alembic commands ###
