"""add can_move to GameUnit

Revision ID: c2b6b6f8a1d7
Revises: 165832e28d4a
Create Date: 2026-02-23 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c2b6b6f8a1d7"
down_revision: Union[str, None] = "165832e28d4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game_units", sa.Column("can_move", sa.Boolean(), nullable=True))
    op.execute("UPDATE game_units SET can_move = TRUE WHERE can_move IS NULL")
    op.alter_column("game_units", "can_move", existing_type=sa.Boolean(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game_units", "can_move")
    # ### end Alembic commands ###
