"""updated map tiles to account for timed effects

Revision ID: dd0d1008feb0
Revises: 0c8901ea0afd
Create Date: 2026-03-30 14:34:40.518712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd0d1008feb0'
down_revision: Union[str, None] = '0c8901ea0afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
