"""added states

Revision ID: ec5b01d4fc59
Revises: dd0d1008feb0
Create Date: 2026-04-06 23:38:08.463244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec5b01d4fc59'
down_revision: Union[str, None] = 'dd0d1008feb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_units', sa.Column('states', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_units', 'states')
    # ### end Alembic commands ###
