FROM python:3.11-slim

WORKDIR /app

# These files are inside the build context (./apps/backend)
COPY requirements.txt .
COPY requirements.dev.txt .

RUN pip install --no-cache-dir -r requirements.dev.txt

# Copy the rest of the app's code (all from /apps/backend)
COPY . .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
