"""One-time generator for ability seed JSON files. Run from apps/backend:

    python scripts/generate_ability_seeds.py
"""

from __future__ import annotations

import json
import os
import re

ABILITIES_DIR = os.path.join(os.path.dirname(__file__), "../seed/abilities")

# (id, name, description, generation)
ABILITIES = [
    (1, "Stench", "When the Pokémon deals damage with its moves, there is a 10% chance that targets will flinch.", 3),
    (2, "Drizzle", "Summons rain for 5 turns when the Pokémon enters a battle.", 3),
    (3, "Speed Boost", "Boosts the Pokémon's Speed stat by 1 stage at the end of every turn.", 3),
    (4, "Battle Armor", "Attacks landed on the Pokémon will never be critical hits.", 3),
    (5, "Sturdy", "If the Pokémon has full HP and takes damage from a move that would knock it out in one hit, it will endure the hit with 1 HP. The Pokémon is also immune to one-hit KO moves.", 3),
    (6, "Damp", "All Pokémon become unable to use explosive moves. Explosive Abilities also fail to trigger.", 3),
    (7, "Limber", "The Pokémon cannot be paralyzed.", 3),
    (8, "Sand Veil", "Boosts the Pokémon's evasiveness by 25% in a sandstorm.", 3),
    (9, "Static", "When the Pokémon is hit by a contact move, the attacker has a 30% chance of being paralyzed.", 3),
    (10, "Volt Absorb", "Electric-type moves do not work on the Pokémon. Instead, they restore 1/4 of its max HP.", 3),
    (11, "Water Absorb", "Water-type moves do not work on the Pokémon. Instead, they restore 1/4 of its max HP.", 3),
    (12, "Oblivious", "The Pokémon cannot gain the Infatuated or Taunted statuses and is unaffected by Intimidate.", 3),
    (13, "Cloud Nine", "Eliminates the effects of weather.", 3),
    (14, "Compound Eyes", "Boosts the accuracy of the Pokémon's moves by 30%.", 3),
    (15, "Insomnia", "The Pokémon cannot become drowsy or be put to sleep.", 3),
    (16, "Color Change", "The Pokémon's type becomes the type of the move used on it.", 3),
    (17, "Immunity", "The Pokémon cannot be poisoned or badly poisoned.", 3),
    (18, "Flash Fire", "Fire-type moves do not work on the Pokémon. Instead, they give the Pokémon the Flash Fire status.", 3),
    (19, "Shield Dust", "The Pokémon is immune to additional effects from attacks.", 3),
    (20, "Own Tempo", "The Pokémon cannot become confused and is unaffected by Intimidate.", 3),
    (21, "Suction Cups", "The Pokémon is unaffected by the moves and held items of other Pokémon that would force it to switch out of battle.", 3),
    (22, "Intimidate", "When the Pokémon enters a battle, it lowers the Attack stats of opponents by 1 stage.", 3),
    (23, "Shadow Tag", "Opponents cannot be switched out of battle.", 3),
    (24, "Rough Skin", "When the Pokémon is hit by a contact move, the attacker takes damage equal to 1/8 of its max HP.", 3),
    (25, "Wonder Guard", "Its mysterious power only lets supereffective moves hit the Pokémon.", 3),
    (26, "Levitate", "The Pokémon floats off the ground, making it immune to Ground-type moves, as well as the Spikes, Toxic Spikes, and Sticky Web statuses.", 3),
    (27, "Effect Spore", "Contact with the Pokémon may inflict poison, sleep, or paralysis on the attacker.", 3),
    (28, "Synchronize", "If the Pokémon is burned, paralyzed, poisoned, or badly poisoned by another Pokémon's move or Ability, that Pokémon will also be inflicted with the same status condition.", 3),
    (29, "Clear Body", "The Pokémon's stats cannot be lowered by other Pokémon's moves or Abilities.", 3),
    (30, "Natural Cure", "The Pokémon's status conditions are cured when it switches out of battle.", 3),
    (31, "Lightning Rod", "The Pokémon draws in all Electric-type moves. These moves do not work on the Pokémon. Instead, they boost its Sp. Atk stat by 1 stage.", 3),
    (32, "Serene Grace", "Raises the likelihood of additional effects occurring when the Pokémon uses its moves.", 3),
    (33, "Swift Swim", "Doubles the Pokémon's Speed stat in rain.", 3),
    (34, "Chlorophyll", "Doubles the Pokémon's Speed stat in harsh sunlight.", 3),
    (35, "Illuminate", "The Pokémon ignores changes to targets' evasiveness and its accuracy cannot be lowered.", 3),
    (36, "Trace", "When the Pokémon enters a battle, it changes its Ability to match that of an opponent.", 3),
    (37, "Huge Power", "Doubles the power of the Pokémon's physical moves.", 3),
    (38, "Poison Point", "When the Pokémon is hit by a contact move, the attacker has a 30% chance of being poisoned.", 3),
    (39, "Inner Focus", "The Pokémon never flinches when attacked and is unaffected by Intimidate.", 3),
    (40, "Magma Armor", "The Pokémon cannot be frozen.", 3),
    (41, "Water Veil", "The Pokémon's water veil prevents it from being burned.", 3),
    (42, "Magnet Pull", "Prevents Steel-type Pokémon from fleeing by pulling them in with magnetism.", 3),
    (43, "Soundproof", "The Pokémon is immune to sound-based moves.", 3),
    (44, "Rain Dish", "The Pokémon has 1/16 of its max HP restored at the end of every turn in rain.", 3),
    (45, "Sand Stream", "Summons a sandstorm for 5 turns when the Pokémon enters a battle.", 3),
    (46, "Pressure", "Causes opponents to expend 1 more PP when using moves against the Pokémon.", 3),
    (47, "Thick Fat", "Halves the damage the Pokémon takes from Fire- and Ice-type moves.", 3),
    (48, "Early Bird", "The Pokémon awakens from sleep twice as fast as other Pokémon.", 3),
    (49, "Flame Body", "When the Pokémon is hit by a contact move, the attacker has a 30% chance of being burned.", 3),
    (50, "Run Away", "Enables a sure getaway from wild Pokémon.", 3),
    (51, "Keen Eye", "The Pokémon ignores changes to targets' evasiveness and its accuracy cannot be lowered.", 3),
    (52, "Hyper Cutter", "The Pokémon's Attack stat cannot be lowered by other Pokémon's moves or Abilities.", 3),
    (53, "Pickup", "If the Pokémon is not already holding an item, at the end of the turn it will pick up an item that was consumed by another Pokémon.", 3),
    (54, "Truant", "Each time the Pokémon uses a move, it spends the next turn loafing around.", 3),
    (55, "Hustle", "When the Pokémon uses physical moves, its Attack stat is boosted by 50%, but its accuracy is lowered by 20%.", 3),
    (56, "Cute Charm", "When the Pokémon is hit by a contact move, the attacker has a 30% chance of gaining the Infatuated status if the attacker and the Pokémon are of opposite genders.", 3),
    (57, "Plus", "Boosts the Pokémon's Sp. Atk stat by 50% if an ally with the Plus or Minus Ability is also in battle.", 3),
    (58, "Minus", "Boosts the Pokémon's Sp. Atk stat by 50% if an ally with the Plus or Minus Ability is also in battle.", 3),
    (59, "Forecast", "The Pokémon transforms with the weather to change its type to Water, Fire, or Ice.", 3),
    (60, "Sticky Hold", "The Pokémon's held item cannot be stolen or removed by other Pokémon.", 3),
    (61, "Shed Skin", "The Pokémon has a 30% chance of curing its own status conditions at the end of every turn.", 3),
    (62, "Guts", "When the Pokémon has a status condition, its Attack stat is boosted by 50%. Being burned does not halve the damage dealt by the Pokémon's physical moves.", 3),
    (63, "Marvel Scale", "When the Pokémon has a status condition, its Defense stat is boosted by 50%.", 3),
    (64, "Liquid Ooze", "The strong stench of the Pokémon's oozed liquid damages attackers that use HP-draining moves.", 3),
    (65, "Overgrow", "Boosts the power of the Pokémon's Grass-type moves by 50% when its HP drops to 1/3 or less of its max.", 3),
    (66, "Blaze", "Boosts the power of the Pokémon's Fire-type moves by 50% when its HP drops to 1/3 or less of its max.", 3),
    (67, "Torrent", "Boosts the power of the Pokémon's Water-type moves by 50% when its HP drops to 1/3 or less of its max.", 3),
    (68, "Swarm", "Boosts the power of the Pokémon's Bug-type moves by 50% when its HP drops to 1/3 or less of its max.", 3),
    (69, "Rock Head", "The Pokémon will not lose HP due to recoil damage from its moves.", 3),
    (70, "Drought", "Summons harsh sunlight for 5 turns when the Pokémon enters a battle.", 3),
    (71, "Arena Trap", "Prevents opposing Pokémon from fleeing from battle.", 3),
    (72, "Vital Spirit", "The Pokémon cannot become drowsy or be put to sleep.", 3),
    (73, "White Smoke", "The Pokémon's stats cannot be lowered by other Pokémon's moves or Abilities.", 3),
    (74, "Pure Power", "Doubles the power of the Pokémon's physical moves.", 3),
    (75, "Shell Armor", "Attacks landed on the Pokémon will never be critical hits.", 3),
    (76, "Air Lock", "Eliminates the effects of weather.", 3),
    (77, "Tangled Feet", "Doubles the Pokémon's evasiveness if it is confused.", 4),
    (78, "Motor Drive", "Electric-type moves do not work on the Pokémon. Instead, they boost its Speed stat by 1 stage.", 4),
    (79, "Rivalry", "Boosts the power of the Pokémon's moves by 25% against targets of the same gender, and lowers it by 25% against targets of the opposite gender. The power remains the same as usual if either Pokémon's gender is unknown.", 4),
    (80, "Steadfast", "When the Pokémon flinches, its Speed stat is boosted by 1 stage.", 4),
    (81, "Snow Cloak", "Boosts the Pokémon's evasiveness by 25% in snow.", 4),
    (82, "Gluttony", "If the Pokémon is holding a Berry to be eaten when its HP drops to 1/4 or less of its max, it will instead eat the Berry when its HP drops to 1/2 or less of its max.", 4),
    (83, "Anger Point", "Boosts the Pokémon's Attack stat to its sixth stage when the Pokémon takes a critical hit.", 4),
    (84, "Unburden", "Doubles the Pokémon's Speed stat when its held item is consumed or lost.", 4),
    (85, "Heatproof", "Halves the damage the Pokémon takes from Fire-type moves and from being burned.", 4),
    (86, "Simple", "Doubles the Pokémon's stat changes.", 4),
    (87, "Dry Skin", "Water-type moves do not work on the Pokémon. Instead, they restore 1/4 of its max HP. However, the Pokémon takes 25% more damage from Fire-type moves. The Pokémon has 1/8 of its max HP restored at the end of every turn in rain, but it loses 1/8 of its max HP at the end of every turn in harsh sunlight.", 4),
    (88, "Download", "The Pokémon compares an opposing Pokémon's Defense and Sp. Def stats before raising its own Attack or Sp. Atk stat — whichever will be more effective.", 4),
    (89, "Iron Fist", "Boosts the power of the Pokémon's punching moves by 20%.", 4),
    (90, "Poison Heal", "If poisoned or badly poisoned, the Pokémon has 1/8 of its max HP restored at the end of every turn instead of losing HP.", 4),
    (91, "Adaptability", "Boosts the power of moves of the same type as the Pokémon by 100% instead of 50%.", 4),
    (92, "Skill Link", "The Pokémon's multistrike moves always hit the maximum number of times.", 4),
    (93, "Hydration", "Cures the Pokémon's status conditions at the end of every turn in rain.", 4),
    (94, "Solar Power", "In harsh sunlight, the Pokémon's Sp. Atk stat is boosted by 50%, but it loses 1/8 of its max HP at the end of every turn.", 4),
    (95, "Quick Feet", "When the Pokémon has a status condition, its Speed stat is boosted by 50%. Being paralyzed does not lower the Pokémon's Speed stat.", 4),
    (96, "Normalize", "All the Pokémon's moves become Normal type. The power of those moves is boosted a little.", 4),
    (97, "Sniper", "Boosts the power of the Pokémon's critical hits by 125% instead of 50%.", 4),
    (98, "Magic Guard", "The Pokémon takes damage only from attacks.", 4),
    (99, "No Guard", "The accuracy of moves used both by and against the Pokémon becomes 100%.", 4),
    (100, "Stall", "The Pokémon's moves go last among moves of the same priority.", 4),
    (101, "Technician", "Boosts the power of the Pokémon's moves by 50% if their power is 60 or less.", 4),
    (102, "Leaf Guard", "The Pokémon is immune to status conditions in harsh sunlight.", 4),
    (103, "Klutz", "Items do not work when held by the Pokémon.", 4),
    (104, "Mold Breaker", "The Pokémon's moves are unaffected by the Ability of the target (with certain exceptions).", 4),
    (105, "Super Luck", "The Pokémon has a 1-stage Critical-Hit Ratio Boost.", 4),
    (106, "Aftermath", "Attackers that knock out the Pokémon with a contact move take damage equal to 1/4 of their max HP.", 4),
    (107, "Anticipation", "When the Pokémon enters a battle, it senses whether the opponents know any one-hit KO moves or moves that are super effective against it.", 4),
    (108, "Forewarn", "When it enters a battle, the Pokémon can tell one of the moves an opposing Pokémon has.", 4),
    (109, "Unaware", "The Pokémon ignores the target's stat changes when attacking, and ignores the attacker's stat changes when being attacked. It cannot ignore changes to the Speed stat, however.", 4),
    (110, "Tinted Lens", "The Pokémon can use \"not very effective\" moves to deal regular damage.", 4),
    (111, "Filter", "Reduces the damage the Pokémon takes from supereffective moves by 25%.", 4),
    (112, "Slow Start", "For five turns, the Pokémon's Attack and Speed stats are halved.", 4),
    (113, "Scrappy", "The Pokémon can hit Ghost types with Normal- and Fighting-type moves. It is also unaffected by Intimidate.", 4),
    (114, "Storm Drain", "The Pokémon draws in all Water-type moves. Instead of taking damage from them, its Sp. Atk stat is boosted.", 4),
    (115, "Ice Body", "The Pokémon has 1/16 of its max HP restored at the end of every turn in snow.", 4),
    (116, "Solid Rock", "Reduces the damage the Pokémon takes from supereffective moves by 25%.", 4),
    (117, "Snow Warning", "Summons snow for 5 turns when the Pokémon enters a battle.", 4),
    (118, "Honey Gather", "The Pokémon may gather Honey after a battle.", 4),
    (119, "Frisk", "When the Pokémon enters a battle, it identifies opponents' held items.", 4),
    (120, "Reckless", "Boosts the power of the Pokémon's moves by 20% if they have recoil or crash damage.", 4),
    (121, "Multitype", "Changes the Pokémon's type to match the plate it holds.", 4),
    (122, "Flower Gift", "Boosts the Attack and Sp. Def stats of the Pokémon and its allies in harsh sunlight.", 4),
    (123, "Bad Dreams", "Damages opposing Pokémon that are asleep.", 4),
    (124, "Pickpocket", "When the Pokémon is hit by a contact move, it will steal the held item of the attacker if it is not already holding an item.", 5),
    (125, "Sheer Force", "The Pokémon's moves lose their additional effects, but the power of those moves will be boosted by 30%.", 5),
    (126, "Contrary", "Reverses any stat changes affecting the Pokémon so that attempts to boost its stats instead lower them—and attempts to lower its stats will boost them.", 5),
    (127, "Unnerve", "Makes opponents unable to eat Berries.", 5),
    (128, "Defiant", "When the Pokémon has any of its stats lowered by an opponent, its Attack stat is boosted by 2 stages.", 5),
    (129, "Defeatist", "Halves the Pokémon's Attack and Sp. Atk stats when its HP drops to half or less.", 5),
    (130, "Cursed Body", "When the Pokémon takes damage from a move, the attacker has a 30% chance of gaining the Move Disabled status for 4 turns.", 5),
    (131, "Healer", "The Pokémon has a 50% chance of curing the status conditions of its allies at the end of every turn.", 5),
    (132, "Friend Guard", "Reduces the damage allies take by 25%.", 5),
    (133, "Weak Armor", "When the Pokémon takes damage from a physical move, its Defense stat is lowered by 1 stage, but its Speed stat is boosted by 2 stages.", 5),
    (134, "Heavy Metal", "Doubles the Pokémon's weight.", 5),
    (135, "Light Metal", "Halves the Pokémon's weight.", 5),
    (136, "Multiscale", "Halves the damage the Pokémon takes while its HP is full.", 5),
    (137, "Toxic Boost", "Powers up physical moves when the Pokémon is poisoned.", 5),
    (138, "Flare Boost", "Powers up special moves when the Pokémon is burned.", 5),
    (139, "Harvest", "If the Pokémon has used a Berry, it has a 50% chance of creating another one at the end of every turn. In harsh sunlight, the Pokémon will definitely create a Berry.", 5),
    (140, "Telepathy", "The Pokémon dodges attacks from its allies.", 5),
    (141, "Moody", "At the end of every turn, one of the Pokémon's stats will be boosted by 2 stages, but another will be lowered by 1 stage.", 5),
    (142, "Overcoat", "The Pokémon takes no damage from sandstorms and is immune to moves and Abilities involving powder.", 5),
    (143, "Poison Touch", "When the Pokémon hits a target with a contact move, the target has a 30% chance of being poisoned.", 5),
    (144, "Regenerator", "The Pokémon has 1/3 of its max HP restored when it switches out of battle.", 5),
    (145, "Big Pecks", "The Pokémon's Defense stat cannot be lowered by other Pokémon's moves or Abilities.", 5),
    (146, "Sand Rush", "Doubles the Pokémon's Speed stat in a sandstorm.", 5),
    (147, "Wonder Skin", "Makes status moves more likely to miss the Pokémon.", 5),
    (148, "Analytic", "Boosts the power of the Pokémon's moves by 30% when the Pokémon is the last to move that turn.", 5),
    (149, "Illusion", "The Pokémon enters battle disguised as the last Pokémon in its party. It reverts to its usual appearance when it takes damage from a move.", 5),
    (150, "Imposter", "The Pokémon transforms into the Pokémon in front of it. It also copies all of that Pokémon's stats apart from its HP.", 5),
    (151, "Infiltrator", "When using its moves, the Pokémon ignores the effects of targets' Light Screen, Reflect, Aurora Veil, Safeguard, and substitutes.", 5),
    (152, "Mummy", "When the Pokémon is hit by a contact move, the attacker has its Ability changed to Mummy.", 5),
    (153, "Moxie", "When the Pokémon knocks out a target with an attack, its Attack stat is boosted by 1 stage.", 5),
    (154, "Justified", "When the Pokémon takes damage from a Dark-type move, its Attack stat is boosted by 1 stage.", 5),
    (155, "Rattled", "The Pokémon gets scared when hit by a Dark-, Ghost-, or Bug-type attack or if intimidated, which boosts its Speed stat.", 5),
    (156, "Magic Bounce", "Instead of being affected by other Pokémon's status moves, the Pokémon bounces them back at the user.", 5),
    (157, "Sap Sipper", "Grass-type moves do not work on the Pokémon. Instead, they boost its Attack stat by 1 stage.", 5),
    (158, "Prankster", "Increases the priority of the Pokémon's status moves by 1 stage.", 5),
    (159, "Sand Force", "Boosts the power of the Pokémon's Rock-, Ground-, and Steel-type moves by 30% in a sandstorm.", 5),
    (160, "Iron Barbs", "The Pokémon's iron barbs damage the attacker if it makes direct contact.", 5),
    (161, "Zen Mode", "Changes the Pokémon's shape when its HP drops to half or less.", 5),
    (162, "Victory Star", "Boosts the accuracy of the Pokémon and its allies.", 5),
    (163, "Turboblaze", "The Pokémon's moves are unimpeded by the Ability of the target.", 5),
    (164, "Teravolt", "The Pokémon's moves are unimpeded by the Ability of the target.", 5),
    (165, "Aroma Veil", "The Pokémon and its allies cannot gain the Infatuated, Taunted, Unable to Repeat, Move Disabled, Healing Prevented, or Encore statuses.", 6),
    (166, "Flower Veil", "Grass-type allies are immune to status conditions and cannot have their stats lowered.", 6),
    (167, "Cheek Pouch", "The Pokémon has 1/3 of its max HP restored when it eats a Berry, in addition to the Berry's usual effect.", 6),
    (168, "Protean", "Changes the Pokémon's type to the type of the move it's about to use. This works only once per time the Pokémon enters battle.", 6),
    (169, "Fur Coat", "Halves the damage the Pokémon takes from physical moves.", 6),
    (170, "Magician", "If the Pokémon is not already holding an item, it will steal the held item from targets it deals damage to with its moves.", 6),
    (171, "Bulletproof", "The Pokémon is immune to ball and bomb moves.", 6),
    (172, "Competitive", "When the Pokémon has any of its stats lowered by an opponent, its Sp. Atk stat is boosted by 2 stages.", 6),
    (173, "Strong Jaw", "Boosts the power of the Pokémon's biting moves by 50%.", 6),
    (174, "Refrigerate", "The Pokémon's Normal-type moves become Ice-type moves and their power is boosted by 20%.", 6),
    (175, "Sweet Veil", "The Pokémon and its allies cannot become drowsy or be put to sleep.", 6),
    (176, "Stance Change", "The Pokémon changes into its Blade Forme when it attacks and changes into its Shield Forme when it uses the move King's Shield.", 6),
    (177, "Gale Wings", "Increases the priority of the Pokémon's Flying-type moves by 1 stage while its HP is full.", 6),
    (178, "Mega Launcher", "Boosts the power of the Pokémon's pulse moves by 50%.", 6),
    (179, "Grass Pelt", "Boosts the Pokémon's Defense stat on Grassy Terrain.", 6),
    (180, "Symbiosis", "When an ally consumes an item, the Pokémon gives its own held item to that ally.", 6),
    (181, "Tough Claws", "Boosts the power of the Pokémon's contact moves by 30%.", 6),
    (182, "Pixilate", "The Pokémon's Normal-type moves become Fairy-type moves and their power is boosted by 20%.", 6),
    (183, "Gooey", "When the Pokémon is hit by a contact move, the attacker's Speed stat is lowered by 1 stage.", 6),
    (184, "Aerilate", "The Pokémon's Normal-type moves become Flying-type moves and their power is boosted by 20%.", 6),
    (185, "Parental Bond", "The parent and child attack one after the other. The power of the child's attacks is 1/4 of those of the parent.", 6),
    (186, "Dark Aura", "Powers up the Dark-type moves of all Pokémon on the field.", 6),
    (187, "Fairy Aura", "Boosts the power of the Fairy-type moves of all Pokémon on the field by 33%.", 6),
    (188, "Aura Break", "The effects of \"Aura\" Abilities are reversed to lower the power of affected moves.", 6),
    (189, "Primordial Sea", "The Pokémon changes the weather to nullify Fire-type attacks.", 6),
    (190, "Desolate Land", "The Pokémon changes the weather to nullify Water-type attacks.", 6),
    (191, "Delta Stream", "The Pokémon changes the weather so that no moves are supereffective against the Flying type.", 6),
    (192, "Stamina", "When the Pokémon takes damage from a move, its Defense stat is boosted by 1 stage.", 7),
    (193, "Wimp Out", "The Pokémon cowardly switches out when its HP drops to half or less.", 7),
    (194, "Emergency Exit", "The Pokémon, sensing danger, switches out when its HP drops to half or less.", 7),
    (195, "Water Compaction", "Boosts the Defense stat sharply when the Pokémon is hit by a Water-type move.", 7),
    (196, "Merciless", "The Pokémon's attacks become critical hits if the target is poisoned or badly poisoned.", 7),
    (197, "Shields Down", "When its HP drops to half or less, the Pokémon's shell breaks and it becomes aggressive.", 7),
    (198, "Stakeout", "Doubles the damage dealt to a target that has just switched into battle.", 7),
    (199, "Water Bubble", "Halves the damage the Pokémon takes from Fire-type moves and doubles the power of its Water-type moves. The Pokémon cannot be burned.", 7),
    (200, "Steelworker", "Powers up Steel-type moves.", 7),
    (201, "Berserk", "Boosts the Pokémon's Sp. Atk stat by 1 stage when an attack causes its HP to drop to 1/2 or less of its max.", 7),
    (202, "Slush Rush", "Doubles the Pokémon's Speed stat in snow.", 7),
    (203, "Long Reach", "None of the moves used by the Pokémon are considered contact moves.", 7),
    (204, "Liquid Voice", "The Pokémon's sound-based moves become Water-type moves.", 7),
    (205, "Triage", "Gives priority to the Pokémon's healing moves.", 7),
    (206, "Galvanize", "Normal-type moves become Electric-type moves. The power of those moves is boosted a little.", 7),
    (207, "Surge Surfer", "Doubles the Pokémon's Speed stat on Electric Terrain.", 7),
    (208, "Schooling", "When it has a lot of HP, the Pokémon forms a powerful school. It stops schooling when its HP is low.", 7),
    (209, "Disguise", "When the Pokémon is in its Disguised Form and would take damage from a move, it loses 1/8 of its max HP instead of taking the damage, then changes into its Busted Form.", 7),
    (210, "Battle Bond", "When the Pokémon knocks out a target, its bond with its Trainer is strengthened, and its Attack, Sp. Atk, and Speed stats are boosted.", 7),
    (211, "Power Construct", "Cells gather to aid the Pokémon when its HP drops to half or less, causing it to change into its Complete Forme.", 7),
    (212, "Corrosion", "The Pokémon can poison or badly poison targets even if they're Steel or Poison types.", 7),
    (213, "Comatose", "The Pokémon is always drowsing and will never wake up. It can attack while in its sleeping state.", 7),
    (214, "Queenly Majesty", "Opponents are unable to use priority moves against the Pokémon or its allies.", 7),
    (215, "Innards Out", "When the Pokémon takes damage from a move that knocks it out, it deals the same amount of damage to the attacker.", 7),
    (216, "Dancer", "Whenever a dance move is used in battle, the Pokémon will copy the user to immediately perform that dance move itself.", 7),
    (217, "Battery", "Powers up ally Pokémon's special moves.", 7),
    (218, "Fluffy", "Halves the damage taken from moves that make direct contact, but doubles that of Fire-type moves.", 7),
    (219, "Dazzling", "The Pokémon dazzles its opponents, making them unable to use priority moves against the Pokémon or its allies.", 7),
    (220, "Soul-Heart", "Boosts the Pokémon's Sp. Atk stat every time another Pokémon faints.", 7),
    (221, "Tangling Hair", "Contact with the Pokémon lowers the attacker's Speed stat.", 7),
    (222, "Receiver", "The Pokémon changes its Ability to match that of a defeated ally.", 7),
    (223, "Power of Alchemy", "The Pokémon copies the Ability of a defeated ally.", 7),
    (224, "Beast Boost", "Boosts the Pokémon's most proficient stat every time it knocks out a target.", 7),
    (225, "RKS System", "Changes the Pokémon's type to match the memory disc it holds.", 7),
    (226, "Electric Surge", "Turns the ground into Electric Terrain when the Pokémon enters a battle.", 7),
    (227, "Psychic Surge", "Turns the ground into Psychic Terrain when the Pokémon enters a battle.", 7),
    (228, "Misty Surge", "Turns the ground into Misty Terrain when the Pokémon enters a battle.", 7),
    (229, "Grassy Surge", "Turns the ground into Grassy Terrain when the Pokémon enters a battle.", 7),
    (230, "Full Metal Body", "Prevents other Pokémon's moves or Abilities from lowering the Pokémon's stats.", 7),
    (231, "Shadow Shield", "Reduces the amount of damage the Pokémon takes while its HP is full.", 7),
    (232, "Prism Armor", "Reduces the power of supereffective attacks that hit the Pokémon.", 7),
    (233, "Neuroforce", "Powers up the Pokémon's supereffective attacks even further.", 7),
    (234, "Intrepid Sword", "Boosts the Pokémon's Attack stat the first time the Pokémon enters a battle.", 8),
    (235, "Dauntless Shield", "Boosts the Pokémon's Defense stat the first time the Pokémon enters a battle.", 8),
    (236, "Libero", "Changes the Pokémon's type to the type of the move it's about to use. This works only once each time the Pokémon enters battle.", 8),
    (237, "Ball Fetch", "If the Pokémon is not holding an item, it will fetch the Poké Ball from the first failed throw of the battle.", 8),
    (238, "Cotton Down", "When the Pokémon is hit by an attack, it scatters cotton fluff around and lowers the Speed stats of all Pokémon except itself.", 8),
    (239, "Propeller Tail", "Ignores the effects of opposing Pokémon's Abilities and moves that draw in moves.", 8),
    (240, "Mirror Armor", "Instead of being affected by stat-lowering effects, the Pokémon bounces them back at whichever Pokémon caused them.", 8),
    (241, "Gulp Missile", "When the Pokémon uses Surf or Dive, it will come back with prey. When it takes damage, it will spit out the prey to attack.", 8),
    (242, "Stalwart", "The Pokémon ignores the effects of Abilities and moves that draw in moves.", 8),
    (243, "Steam Engine", "Boosts the Speed stat drastically when the Pokémon is hit by a Fire- or Water-type move.", 8),
    (244, "Punk Rock", "Boosts the power of sound-based moves. The Pokémon also takes half the damage from these kinds of moves.", 8),
    (245, "Sand Spit", "Summons a sandstorm for 5 turns when the Pokémon takes damage from moves.", 8),
    (246, "Ice Scales", "The Pokémon is protected by ice scales, which halve the damage taken from special moves.", 8),
    (247, "Ripen", "Doubles the effects of Berries eaten by the Pokémon.", 8),
    (248, "Ice Face", "The Pokémon's ice head can take a physical attack as a substitute, but the attack also changes the Pokémon's appearance. The ice will be restored when it snows.", 8),
    (249, "Power Spot", "Just being next to the Pokémon powers up moves.", 8),
    (250, "Mimicry", "The Pokémon's type changes depending on the terrain.", 8),
    (251, "Screen Cleaner", "When the Pokémon enters a battle, it removes the Light Screen, Reflect, and Aurora Veil statuses.", 8),
    (252, "Steely Spirit", "Powers up the Steel-type moves of the Pokémon and its allies.", 8),
    (253, "Perish Body", "When hit by a move that makes direct contact, the Pokémon and the attacker will faint after three turns unless they switch out of battle.", 8),
    (254, "Wandering Spirit", "When the Pokémon is hit by a contact move, it swaps Abilities with the attacker.", 8),
    (255, "Gorilla Tactics", "Boosts the Pokémon's Attack stat, but only allows the use of the first selected move.", 8),
    (256, "Neutralizing Gas", "While the Pokémon is in the battle, the effects of all other Pokémon's Abilities will be nullified or will not be triggered.", 8),
    (257, "Pastel Veil", "Prevents the Pokémon and its allies from being poisoned.", 8),
    (258, "Hunger Switch", "The Pokémon changes its form, alternating between its Full Belly Mode and Hangry Mode at the end of every turn.", 8),
    (259, "Quick Draw", "The Pokémon's moves have a 30% chance of going first among moves of the same priority.", 8),
    (260, "Unseen Fist", "When the Pokémon uses contact moves, it can hit even targets that are protecting themselves, dealing 1/4 of the damage that the move would otherwise deal. Everything aside from the target's protective effects is still triggered.", 8),
    (261, "Curious Medicine", "When the Pokémon enters a battle, it removes all stat changes from its allies.", 8),
    (262, "Transistor", "Powers up Electric-type moves.", 8),
    (263, "Dragon's Maw", "Powers up Dragon-type moves.", 8),
    (264, "Chilling Neigh", "When the Pokémon knocks out a target, it utters a chilling neigh, which boosts its Attack stat.", 8),
    (265, "Grim Neigh", "When the Pokémon knocks out a target, it utters a terrifying neigh, which boosts its Sp. Atk stat.", 8),
    (266, "As One", "This Ability combines the effects of both Calyrex's Unnerve Ability and Glastrier's Chilling Neigh Ability.", 8),
    (267, "As One", "This Ability combines the effects of both Calyrex's Unnerve Ability and Spectrier's Grim Neigh Ability.", 8),
    (268, "Lingering Aroma", "Contact with the Pokémon changes the attacker's Ability to Lingering Aroma.", 9),
    (269, "Seed Sower", "Turns the ground into Grassy Terrain when the Pokémon is hit by an attack.", 9),
    (270, "Thermal Exchange", "Boosts the Attack stat when the Pokémon is hit by a Fire-type move. The Pokémon also cannot be burned.", 9),
    (271, "Anger Shell", "When an attack causes its HP to drop to half or less, the Pokémon gets angry. This lowers its Defense and Sp. Def stats but boosts its Attack, Sp. Atk, and Speed stats.", 9),
    (272, "Purifying Salt", "Halves the damage the Pokémon takes from Ghost-type moves. The Pokémon is immune to status conditions.", 9),
    (273, "Well-Baked Body", "The Pokémon takes no damage when hit by Fire-type moves. Instead, its Defense stat is sharply boosted.", 9),
    (274, "Wind Rider", "Boosts the Pokémon's Attack stat if Tailwind takes effect or if the Pokémon is hit by a wind move. The Pokémon also takes no damage from wind moves.", 9),
    (275, "Guard Dog", "Boosts the Pokémon's Attack stat if intimidated. Moves and items that would force the Pokémon to switch out also fail to work.", 9),
    (276, "Rocky Payload", "Powers up Rock-type moves.", 9),
    (277, "Wind Power", "The Pokémon becomes charged when it is hit by a wind move, boosting the power of the next Electric-type move the Pokémon uses.", 9),
    (278, "Zero to Hero", "The Pokémon changes into its Hero Form when it switches out of battle.", 9),
    (279, "Commander", "When the Pokémon enters a battle, it goes inside the mouth of an ally Dondozo if one is on the field. The Pokémon then issues commands from there.", 9),
    (280, "Electromorphosis", "When the Pokémon takes damage from a move, it gains the Electric Boost status.", 9),
    (281, "Protosynthesis", "Boosts the Pokémon's most proficient stat in harsh sunlight or if the Pokémon is holding Booster Energy.", 9),
    (282, "Quark Drive", "Boosts the Pokémon's most proficient stat on Electric Terrain or if the Pokémon is holding Booster Energy.", 9),
    (283, "Good as Gold", "A body of pure, solid gold gives the Pokémon full immunity to other Pokémon's status moves.", 9),
    (284, "Vessel of Ruin", "The power of the Pokémon's ruinous vessel lowers the Sp. Atk stats of all Pokémon except itself.", 9),
    (285, "Sword of Ruin", "The power of the Pokémon's ruinous sword lowers the Defense stats of all Pokémon except itself.", 9),
    (286, "Tablets of Ruin", "The power of the Pokémon's ruinous wooden tablets lowers the Attack stats of all Pokémon except itself.", 9),
    (287, "Beads of Ruin", "The power of the Pokémon's ruinous beads lowers the Sp. Def stats of all Pokémon except itself.", 9),
    (288, "Orichalcum Pulse", "Turns the sunlight harsh when the Pokémon enters a battle. The ancient pulse thrumming through the Pokémon also boosts its Attack stat in harsh sunlight.", 9),
    (289, "Hadron Engine", "Turns the ground into Electric Terrain when the Pokémon enters a battle. The futuristic engine within the Pokémon also boosts its Sp. Atk stat on Electric Terrain.", 9),
    (290, "Opportunist", "When an opponent's stats are boosted, the Pokémon boosts its own stats in the exact same way.", 9),
    (291, "Cud Chew", "If the Pokémon eats a Berry, it will eat that same Berry once more at the end of the next turn.", 9),
    (292, "Sharpness", "Boosts the power of the Pokémon's slicing moves by 50%.", 9),
    (293, "Supreme Overlord", "When the Pokémon enters a battle, the power of its moves is boosted by 10% for each Pokémon in its party that has been defeated in the battle already. The maximum boost is 50%.", 9),
    (294, "Costar", "When the Pokémon enters a battle, it copies an ally's stat changes.", 9),
    (295, "Toxic Debris", "When the Pokémon takes damage from a physical move, it gives the opponent's side the Toxic Spikes status.", 9),
    (296, "Armor Tail", "Opponents are unable to use priority moves against the Pokémon or its allies.", 9),
    (297, "Earth Eater", "Ground-type moves do not work on the Pokémon. Instead, they restore 1/4 of its max HP.", 9),
    (298, "Mycelium Might", "The Pokémon will always act more slowly when using status moves, but these moves will be unimpeded by the Ability of the target.", 9),
    (299, "Hospitality", "When the Pokémon enters a battle, it restores 1/4 of its ally's max HP.", 9),
    (300, "Mind's Eye", "The Pokémon ignores changes to opponents' evasiveness, its accuracy can't be lowered, and it can hit Ghost types with Normal- and Fighting-type moves.", 9),
    (301, "Embody Aspect", "The Pokémon's heart fills with memories, causing the Teal Mask to shine and the Pokémon's Speed stat to be boosted.", 9),
    (302, "Embody Aspect", "The Pokémon's heart fills with memories, causing the Hearthflame Mask to shine and the Pokémon's Attack stat to be boosted.", 9),
    (303, "Embody Aspect", "The Pokémon's heart fills with memories, causing the Wellspring Mask to shine and the Pokémon's Sp. Def stat to be boosted.", 9),
    (304, "Embody Aspect", "The Pokémon's heart fills with memories, causing the Cornerstone Mask to shine and the Pokémon's Defense stat to be boosted.", 9),
    (305, "Toxic Chain", "The power of the Pokémon's toxic chain may badly poison any target the Pokémon hits with a move.", 9),
    (306, "Supersweet Syrup", "When the Pokémon enters a battle, opponents' evasiveness is lowered by 1 stage. This Ability is triggered only once per battle.", 9),
    (307, "Tera Shift", "When the Pokémon enters a battle, it absorbs the energy around itself and transforms into its Terastal Form.", 9),
    (308, "Tera Shell", "The Pokémon's shell contains the powers of each type. All damage-dealing moves that hit the Pokémon when its HP is full will not be very effective.", 9),
    (309, "Teraform Zero", "When Terapagos changes into its Stellar Form, it uses its hidden powers to eliminate all effects of weather and terrain, reducing them to zero.", 9),
    (310, "Poison Puppeteer", "Pokémon poisoned by Pecharunt's moves will also become confused.", 9),
]

SLUG_OVERRIDES = {
    266: "as_one_glastrier",
    267: "as_one_spectrier",
    301: "embody_aspect_teal_mask",
    302: "embody_aspect_hearthflame_mask",
    303: "embody_aspect_wellspring_mask",
    304: "embody_aspect_cornerstone_mask",
}


def slugify(name: str) -> str:
    slug = name.lower()
    slug = re.sub(r"['\.]", "", slug)
    slug = re.sub(r"[^a-z0-9]+", "_", slug)
    return slug.strip("_")


def ability_slug(ability_id: int, name: str) -> str:
    return SLUG_OVERRIDES.get(ability_id, slugify(name))


def main() -> None:
    os.makedirs(ABILITIES_DIR, exist_ok=True)
    for ability_id, name, description, generation in ABILITIES:
        slug = ability_slug(ability_id, name)
        gen_dir = os.path.join(ABILITIES_DIR, f"gen{generation}")
        os.makedirs(gen_dir, exist_ok=True)
        payload = {
            "id": ability_id,
            "name": name,
            "slug": slug,
            "description": description,
            "generation": generation,
        }
        path = os.path.join(gen_dir, f"{slug}.json")
        with open(path, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, indent=2, ensure_ascii=False)
            handle.write("\n")
    print(f"✅ Generated {len(ABILITIES)} ability seed files in {ABILITIES_DIR}")


if __name__ == "__main__":
    main()
