services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@poketactics.dev
      PGADMIN_DEFAULT_PASSWORD: supersecure
      PGADMIN_CONFIG_PROXY_X_FOR_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PROTO_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_SCRIPT_NAME_HEADER: "'X-Script-Name'"
      PGADMIN_CONFIG_PROXY: "True"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_COOKIE_SAMESITE: "'Lax'"
      PGADMIN_CONFIG_ALLOW_ROOT: "True"
      PGADMIN_CONFIG_PROXY_X_SCRIPT_NAME: "'/db/admin'"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - ../apps/backend/.env
    depends_on:
      - postgres
      - redis
    volumes:
      - ../apps/backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    env_file:
      - ../apps/frontend/.env
    depends_on:
      - backend
    volumes:
      - ../apps/frontend:/app:cached   
      - ../assets:/app/assets:ro
      - /app/node_modules
      - ../infrastructure/certs:/app/certs:ro 
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev"]

volumes:
  pgadmin_data:
